Add support for Django 5.1.7
Django version 5.1.7 made a backwards incompatible change by removing
the `single_object` kwarg from the `LogEntry.log_actions()` method,
which caused an unexpected keyword argument TypeError.

Refactor `ChangedLogEntryManager.log_actions()` to handle being called
with or without the `single_object` keyword argument in order to support
all Django 5.1 versions.